# 智游助手v6.2 Secret模板
# Week 5-6: CD Pipeline构建 - 敏感信息管理

{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-travel.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-travel.labels" . | nindent 4 }}
type: Opaque
data:
  # 数据库连接配置
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "smart-travel.fullname" .) .Values.postgresql.auth.database | b64enc }}
  {{- else if .Values.secrets.data.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secrets.data.DATABASE_URL | b64enc }}
  {{- end }}
  
  # Redis连接配置
  {{- if .Values.redis.enabled }}
  REDIS_URL: {{ printf "redis://:%s@%s-redis-master:6379" .Values.redis.auth.password (include "smart-travel.fullname" .) | b64enc }}
  {{- else if .Values.secrets.data.REDIS_URL }}
  REDIS_URL: {{ .Values.secrets.data.REDIS_URL | b64enc }}
  {{- end }}
  
  # 外部API密钥
  {{- if .Values.secrets.data.AMAP_API_KEY }}
  AMAP_API_KEY: {{ .Values.secrets.data.AMAP_API_KEY | b64enc }}
  {{- end }}
  
  # JWT密钥
  {{- if .Values.secrets.data.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secrets.data.JWT_SECRET | b64enc }}
  {{- end }}
  
  # 支付网关配置
  {{- if .Values.secrets.data.PAYMENT_GATEWAY_KEY }}
  PAYMENT_GATEWAY_KEY: {{ .Values.secrets.data.PAYMENT_GATEWAY_KEY | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.PAYMENT_GATEWAY_SECRET }}
  PAYMENT_GATEWAY_SECRET: {{ .Values.secrets.data.PAYMENT_GATEWAY_SECRET | b64enc }}
  {{- end }}
  
  # 监控系统密钥
  {{- if .Values.secrets.data.PROMETHEUS_TOKEN }}
  PROMETHEUS_TOKEN: {{ .Values.secrets.data.PROMETHEUS_TOKEN | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.GRAFANA_API_KEY }}
  GRAFANA_API_KEY: {{ .Values.secrets.data.GRAFANA_API_KEY | b64enc }}
  {{- end }}
  
  # 自定义密钥
  {{- range $key, $value := .Values.secrets.data }}
  {{- if not (has $key (list "DATABASE_URL" "REDIS_URL" "AMAP_API_KEY" "JWT_SECRET" "PAYMENT_GATEWAY_KEY" "PAYMENT_GATEWAY_SECRET" "PROMETHEUS_TOKEN" "GRAFANA_API_KEY")) }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

---
# Harbor镜像仓库访问密钥
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-travel.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.global.imageRegistry (.Values.harbor.username | default "admin") (.Values.harbor.password | default "Harbor12345") (printf "%s:%s" (.Values.harbor.username | default "admin") (.Values.harbor.password | default "Harbor12345") | b64enc) | b64enc }}
