# 智游助手v6.2 Prometheus配置
# 基于现有架构的监控指标收集

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smart-travel-v6.2'
    environment: 'development'

# 告警规则文件
rule_files:
  - "/etc/prometheus/rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 监控目标配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # 智游助手v6.2应用监控（基于现有健康检查扩展）
  - job_name: 'smart-travel-app'
    static_configs:
      - targets: ['192.168.147.1:3001']  # 连接到主机上的应用（端口3001）
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /api/metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-app'
      - source_labels: [__address__]
        target_label: service
        replacement: 'smart-travel-v6.2'

  # 智游助手v6.2测试监控端点
  - job_name: 'smart-travel-test'
    static_configs:
      - targets: ['192.168.147.1:3003']  # 测试服务器端口3003
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-test'
      - source_labels: [__address__]
        target_label: service
        replacement: 'smart-travel-v6.2-test'

  # 系统指标监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-server'

  # Redis监控（连接现有Redis）
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-redis'

  # MySQL监控（连接现有MySQL）
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-mysql'

  # 容器监控
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smart-travel-containers'

  # Grafana监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # AlertManager监控
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: /metrics

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:9201/read"
