# GitLab Runner 配置
# 智游助手v6.2 CI/CD Runner配置

concurrent = 4
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "smart-travel-docker-runner"
  url = "https://gitlab.smarttravel.local/"
  token = "YOUR_RUNNER_TOKEN"
  executor = "docker"
  
  [runners.custom_build_dir]
  
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  
  [runners.docker]
    tls_verify = false
    image = "node:18-alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock",
      "/cache",
      "/builds:/builds"
    ]
    shm_size = 0
    network_mode = "gitlab_gitlab_network"
    
    # 预拉取常用镜像
    pull_policy = ["if-not-present"]
    
    # 资源限制
    memory = "2g"
    memory_swap = "2g"
    cpus = "2"
    
    # 环境变量
    environment = [
      "DOCKER_DRIVER=overlay2",
      "DOCKER_TLS_CERTDIR="
    ]

[[runners]]
  name = "smart-travel-kubernetes-runner"
  url = "https://gitlab.smarttravel.local/"
  token = "YOUR_K8S_RUNNER_TOKEN"
  executor = "kubernetes"
  
  [runners.kubernetes]
    host = "https://kubernetes.default.svc"
    namespace = "gitlab-runner"
    privileged = true
    image = "node:18-alpine"
    
    # 资源配置
    cpu_limit = "2"
    memory_limit = "2Gi"
    cpu_request = "500m"
    memory_request = "512Mi"
    
    # 存储配置
    [[runners.kubernetes.volumes.empty_dir]]
      name = "docker-certs"
      mount_path = "/certs/client"
      medium = "Memory"
    
    [[runners.kubernetes.volumes.host_path]]
      name = "docker-sock"
      mount_path = "/var/run/docker.sock"
      host_path = "/var/run/docker.sock"
    
    # 服务配置
    [runners.kubernetes.services]
      [[runners.kubernetes.services]]
        name = "docker"
        image = "docker:24-dind"
        privileged = true
        environment = [
          "DOCKER_TLS_CERTDIR=/certs"
        ]
        [[runners.kubernetes.services.volumes.empty_dir]]
          name = "docker-certs"
          mount_path = "/certs/client"
          medium = "Memory"

[[runners]]
  name = "smart-travel-shell-runner"
  url = "https://gitlab.smarttravel.local/"
  token = "YOUR_SHELL_RUNNER_TOKEN"
  executor = "shell"
  
  [runners.cache]
    Type = "local"
    Path = "/tmp/gitlab-runner-cache"
    Shared = true
  
  # Shell runner用于特殊任务
  shell = "bash"
  
  [runners.custom_build_dir]
    enabled = true
