# Harbor 镜像仓库部署配置
# 智游助手v6.2 容器镜像管理

version: '3.8'

services:
  # Harbor核心服务
  harbor-core:
    image: goharbor/harbor-core:v2.9.0
    container_name: harbor-core
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_data:/data
      - ./config/core/app.conf:/etc/core/app.conf:z
      - ./config/core/private_key.pem:/etc/core/private_key.pem:z
      - ./config/shared/trust-certificates:/harbor_cust_cert:z
    networks:
      - harbor
    depends_on:
      - harbor-log
      - harbor-db
      - harbor-redis
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-core"

  # Harbor Portal (Web UI)
  harbor-portal:
    image: goharbor/harbor-portal:v2.9.0
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./config/portal/nginx.conf:/etc/nginx/nginx.conf:z
    networks:
      - harbor
    depends_on:
      - harbor-log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-portal"

  # Harbor Registry
  harbor-registry:
    image: goharbor/registry-photon:v2.9.0
    container_name: harbor-registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_registry:/storage
      - ./config/registry/:/etc/registry/:z
      - ./config/shared/trust-certificates:/harbor_cust_cert:z
    networks:
      - harbor
    depends_on:
      - harbor-log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-registry"

  # Harbor Registry Controller
  harbor-registryctl:
    image: goharbor/harbor-registryctl:v2.9.0
    container_name: harbor-registryctl
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_registry:/storage
      - ./config/registry/:/etc/registry/:z
      - ./config/registryctl/env:z
      - ./config/shared/trust-certificates:/harbor_cust_cert:z
    networks:
      - harbor
    depends_on:
      - harbor-log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-registryctl"

  # Harbor Database (PostgreSQL)
  harbor-db:
    image: goharbor/harbor-db:v2.9.0
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_db:/var/lib/postgresql/data
    networks:
      - harbor
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: registry
      POSTGRES_USER: postgres
    depends_on:
      - harbor-log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-db"

  # Harbor Redis
  harbor-redis:
    image: goharbor/redis-photon:v2.9.0
    container_name: harbor-redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_redis:/var/lib/redis
    networks:
      - harbor
    depends_on:
      - harbor-log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-redis"

  # Harbor Job Service
  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.9.0
    container_name: harbor-jobservice
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_data:/data
      - ./config/jobservice/config.yml:/etc/jobservice/config.yml:z
      - ./config/shared/trust-certificates:/harbor_cust_cert:z
    networks:
      - harbor
    depends_on:
      - harbor-log
      - harbor-db
      - harbor-redis
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-jobservice"

  # Harbor Proxy (Nginx)
  harbor-proxy:
    image: goharbor/nginx-photon:v2.9.0
    container_name: harbor-proxy
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./config/nginx:/etc/nginx:z
      - ./ssl:/etc/nginx/cert:z
    networks:
      - harbor
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - harbor-log
      - harbor-core
      - harbor-portal
      - harbor-registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-proxy"

  # Harbor Log
  harbor-log:
    image: goharbor/harbor-log:v2.9.0
    container_name: harbor-log
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor_log:/var/log/docker/
      - ./config/log/logrotate.conf:/etc/logrotate.d/logrotate.conf:z
      - ./config/log/rsyslog_docker.conf:/etc/rsyslog.d/rsyslog_docker.conf:z
    networks:
      - harbor
    ports:
      - 127.0.0.1:1514:10514

  # Trivy安全扫描器
  harbor-trivy:
    image: goharbor/trivy-adapter-photon:v2.9.0
    container_name: harbor-trivy
    restart: always
    cap_drop:
      - ALL
    volumes:
      - harbor_trivy:/home/scanner/.cache/trivy
      - ./config/trivy/env:z
    networks:
      - harbor
    depends_on:
      - harbor-log
      - harbor-redis
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "harbor-trivy"

volumes:
  harbor_data:
    driver: local
  harbor_registry:
    driver: local
  harbor_db:
    driver: local
  harbor_redis:
    driver: local
  harbor_log:
    driver: local
  harbor_trivy:
    driver: local

networks:
  harbor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
